services:
  mysql:
    image: 'mysql:latest'
    container_name: 'multi-threaded-api-mysql'
    environment:
      - 'MYSQL_DATABASE=multithread'
      - 'MYSQL_PASSWORD=root'
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_USER=guest'
    ports:
      - '3306:3306'
